name: Sync Fork

on:
  push:
    paths:
      - '.github/workflows/sync-fork.yml'  
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点运行
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Merge upstream changes
        run: |
          git remote add upstream https://github.com/sbwml/luci-theme-argon.git
          git fetch upstream
          git merge upstream/openwrt-23.05 --allow-unrelated-histories --no-edit || exit 1

      - name: Push changes
        run: git push
